# Generated by Django 5.0.6 on 2024-05-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(verbose_name='last login')),
            ],
        ),
    ]
